language: python
cache: pip
sudo: required
services:
- docker

before_script:
- docker build -t builder .

script:
- docker run --rm -v $PWD/dist:/dist builder cp36-cp36m 3.6.5
- docker run --rm -v $PWD/dist:/dist builder cp37-cp37m 3.6.5
- docker run --rm -v $PWD/dist:/dist builder cp38-cp38 3.6.5
- cp dist/*.whl test/
- for OS in test/Dockerfile*; do echo $OS; docker build -f $OS test; done

# Travis encryption where GITHUB_KEY is
# a GitHub token with public_repo access
# --------------------------------------
# docker run -it --rm ruby bash
# gem install travis
# travis encrypt -r ome/zeroc-ice-py-manylinux $GITHUB_KEY
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/zeroc*
  skip_cleanup: true
  on:
    tags: true
